version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - Guts
    labels:
      - dependencies

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - Guts
    labels:
      - ci-cd
