[build]
publish = "site"
command = """
python -m pip install --upgrade pip setuptools wheel
python -m pip install -r requirements.txt
python -m mkdocs build --config-file src/mkdocs/mkdocs.yml --verbose --strict
"""
