name: "📝 Proposition d'article"
description: "Formulaire de proposition d'article pour Geotribu."
labels: ["contribution externe", "article", "triage"]
assignees:
  - aurelienchaumet
  - guts
  - igeofr

body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de contribuer à Geotribu !
        Le guide de soumission et la structure d'un article [sont ici](https://contribuer.geotribu.fr/articles/workflow/).

  - type: markdown
    attributes:
      value: |
        ----

        # Vous

  - type: checkboxes
    id: cb_author_content_relationship
    attributes:
      label: "Avez-vous un lien avec le contenu proposé ?"
      description: Mise en avant du travail d'un tiers ? Auto-promo ? Publicité ?
      options:
        - label: Oui
        - label: Non
    validations:
      required: true

  - type: checkboxes
    id: cb_author_aware_ai_guidelines
    attributes:
      label: "Êtes-vous au courant des lignes directrices concernant l'usage de l'IA pour les contributions à Geotribu ?"
      description: La contribution doit émaner de votre originalité, et non découler d'un copier / coller issu d'un prompt, comme décrit [dans la charte](https://contribuer.geotribu.fr/requirements/).
      options:
        - label: Oui
    validations:
      required: true

  - type: input
    id: in_author_name
    attributes:
      label: Votre nom
      description: Merci de nous indiquer le Prénom NOM (pseudonyme accepté) sous lequel vous signez l'article (voir [signer ses contributions](https://contribuer.geotribu.fr/guides/authoring/#signer-pour-quelquun-dautre)).
      placeholder: ex. "Jean DUPONT"
    validations:
      required: true

  - type: input
    id: in_author_mail
    attributes:
      label: Votre adresse email
      description: Merci de nous indiquer votre adresse email afin de pouvoir vous signez l'article (voir [signer ses contributions](https://contribuer.geotribu.fr/guides/authoring/#signer-pour-quelquun-dautre)).
      placeholder: ex. pseudo.nyme [à] mon-organisation.fr
    validations:
      required: true

  - type: dropdown
    id: dr_author_license
    attributes:
      label: Licence
      description: |
        Choisissez la licence qui vous convient le mieux. Voir [le guide](https://contribuer.geotribu.fr/guides/licensing/).
      options:
        - "Creative Commons International BY-NC-SA 4.0"
        - "Creative Commons International BY-SA 4.0"
        - "Beerware (Révision 42)"
        - "autre - merci de préciser dans le champ libre en fin de formulaire"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ----

        # L'article

  - type: input
    id: in_art_title
    attributes:
      label: Titre
      description: "Le titre de l'article. Longueur maximale indicative : 100/120 caractères"
    validations:
      required: true

  - type: input
    id: in_art_description
    attributes:
      label: Description courte
      description: "Description de 160 caractères maximum qui résume l'article et qui est présente dans le [flux RSS](https://geotribu.fr/feed_rss_created.xml), la [newsletter](https://us5.campaign-archive.com/home/?u=465e16ce303f65e4f490e8a71&id=6c4efaf092), les moteurs de recherche, en page d'accueil... Pensez en termes de SEO !"
    validations:
      required: true

  - type: input
    id: in_art_tags
    attributes:
      label: Mots-clés
      description: |
        Liste de mots-clés séparés par une virgule.
        De préférence, choisir parmi les [mots-clés existants](https://geotribu.fr/tags/).
    validations:
      required: true

  - type: input
    id: in_art_date
    attributes:
      label: Date de publication envisagée
      description: |
        Pour information, nous avons pour habitude de publier les articles les mardis ou les vendredis sans RDP.
        Afin d'assurer une bonne ventilation des publications, l'équipe se réserve le droit de changer la date.
    validations:
      required: true

  - type: textarea
    id: tx_art_content
    attributes:
      label: Contenu de l'article
      description: |
        Si vous avez déjà votre contenu, collez le ici. Longueur maximale 65536 caractères.
        La syntaxe Markdown est acceptée, mais rappelez-vous que le rendu final est celui de Material for Mkdocs et diffèrera donc de celui de GitHub. Voici [le guide de rédaction avec les principales différences de syntaxe](https://contribuer.geotribu.fr/guides/markdown_quality/#interligne-simple).
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ----

  - type: textarea
    id: tx_misc_comment
    attributes:
      label: Message libre
      description: "Un commentaire ? Une précision à apporter ? Un message pour l'équipe ?"
