name: "PR Linter Comments 💬"

on:
  workflow_run:
    workflows: ["Markdown Linter 🎳"]
    types:
      - completed

jobs:
  comment:
    name: "Linter - Comment on PR"
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.event == 'pull_request' }}

    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        with:
          delete: true
          number: ${{ env.PR_NUMBER }}

      - name: "Download build artifact"
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          name: pr-markdown-lint-report
          run_id: ${{ github.event.workflow_run.id }}
          workflow: pr_linter_markdown.yml

      - name: "Restore preserved ENV"
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: cat pr.env >> "${GITHUB_ENV}"

      - name: Merge reports
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: |
          echo -e ":boom: Erreurs repérées dans la syntaxe Markdown. @${{ env.PR_AUTHOR }} merci de consulter le rapport du linter  :pray:\n" > msg_comment.txt
          cat ma*.txt >> msg_comment.txt

      # in case of failure
      - uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        with:
          recreate: true
          path: msg_comment.txt
